# Generated by Django 2.2.13 on 2020-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mtgCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mana_cost', models.CharField(max_length=200)),
                ('cmc', models.IntegerField()),
                ('colors', models.TextField()),
                ('types', models.TextField()),
                ('rarity', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('power', models.CharField(max_length=200)),
                ('toughness', models.CharField(max_length=200)),
                ('set_name', models.CharField(max_length=200)),
                ('legalities', models.TextField()),
                ('rulings', models.TextField()),
            ],
        ),
    ]
