# Generated by Django 2.2.13 on 2020-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MtgInfoApp', '0002_auto_20200614_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgcard',
            name='rarity',
            field=models.TextField(),
        ),
    ]
