# Generated by Django 2.2.13 on 2020-06-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MtgInfoApp', '0005_auto_20200614_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtgcard',
            name='cmc',
        ),
        migrations.RemoveField(
            model_name='mtgcard',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='mtgcard',
            name='mana_cost',
        ),
        migrations.RemoveField(
            model_name='mtgcard',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='mtgcard',
            name='types',
        ),
    ]
