# Generated by Django 2.2.13 on 2020-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MtgInfoApp', '0006_auto_20200614_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgcard',
            name='artist',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='border',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='cmc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='color_identity',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='colors',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='flavor',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='foreign_names',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='hand',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='layout',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='legalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='life',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='loyalty',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='mana_cost',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='multiverse_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='names',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='original_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='original_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='power',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='printings',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='rarity',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='release_date',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='rulings',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='set',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='set_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='starter',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='subtypes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='supertypes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='timeshifted',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='toughness',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='types',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='variations',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mtgcard',
            name='watermark',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcard',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mtgcard',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='block',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='booster',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='border',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='gatherer_code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='magic_cards_info_code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='mkm_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='mkm_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='old_code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='online_only',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='release_date',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
