# Generated by Django 2.2.13 on 2020-06-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MtgInfoApp', '0007_auto_20200614_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgcard',
            name='cmc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mtgcard',
            name='multiverse_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mtgset',
            name='mkm_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
